from init_arm import *
import time

intialize()

rotation_motion(0)
time.sleep(1)
rotation_motion(10)
time.sleep(1)
rotation_motion(20)
time.sleep(1)
rotation_motion(30)
time.sleep(1)
rotation_motion(40)
time.sleep(1)
rotation_motion(50)
time.sleep(1)
rotation_motion(60)
time.sleep(1)
rotation_motion(70)
time.sleep(1)
rotation_motion(80)
time.sleep(1)
rotation_motion(90)
time.sleep(1)
rotation_motion(100)
time.sleep(1)
rotation_motion(110)
time.sleep(1)
rotation_motion(120)
time.sleep(1)
rotation_motion(130)
time.sleep(1)
rotation_motion(140)
time.sleep(1)
rotation_motion(150)
time.sleep(1)
rotation_motion(160)
time.sleep(1)
rotation_motion(170)
time.sleep(1)
rotation_motion(180)
